name: Deploy Docsify to Firebase Hosting

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
